on: push
name: quality tests
jobs:
  build:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          version: 16.x
      - name: Load repository
        uses: actions/checkout@v3
      - name: Run tests
        timeout-minutes: 30
        run: |
          npm install
          npm run test --coverage
      - name: Fix code coverage paths
        working-directory: ./coverage
        run: sed -i '/home/runner/work/Project_DevOps/Project_DevOps///github/workspace//g' lcov.info
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}