name: deploiement en production

concurrency: production

on: 
  pull_request:
    branches: main

jobs:
  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
      - uses: actions/checkout@v3
      - uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
        #le token et l'URL sont à titre indicatif, car nous ne possédons pas de serveur pour le faire tourner.
          token: "${{ github.token }}"
          target_url: http://my-app-prod.com
          environment: production

  notify:
      name: Discord notification
      runs-on: ubuntu-latest
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      steps:
        - uses: Ilshidur/action-discord@master
          with:
            args: 'The project has been correctly deployed'