name: workflow

on:
  push:
    branches: docker

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag devopstp

  trivy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-results.txt'
          severity: 'CRITICAL'
          exit-code: '1'

      - name: "upload build artifacts"
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: /tmp