name: workflow

on:
  push:
    branches: docker

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag devopstp:$(date +%s)
